WebApplication(ASP-MVC)/Models/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication_ASP_MVC_.Models
{
    public class Blog
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [DisplayName("Judul")]
        public string Title { get; set; }
        [Required]
        [DisplayName("Isinya")]
        public string Content { get; set; }
        [Required]
        [DisplayName("Tanggal Pembuatan")]
        public DateTime CreateDate { get; set; }
        public string Image { get; set; }
        public bool Status { get; set; }
        public User User { get; set; }
    }

    public class BlogDashboard
    {
        public List<Blog> blog { get; set; }
        public List<User> user { get; set; }

        public BlogDashboard()
        {
            blog = new List<Blog>();
            user = new List<User>();
        }
    }

    public class DetailBlog
    {
        public List<Blog> blog { get; set; }

        public DetailBlog()
        {
            blog = new List<Blog>();
        }
    }

}

WebApplication(ASP-MVC)/Controllers/BlogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication_ASP_MVC_.Helper;
using WebApplication_ASP_MVC_.Models;
using WebApplication_ASP_MVC_.Services;

namespace WebApplication_ASP_MVC_.Controllers
{
    [Authorize]
    public class BlogController : Controller
    { 
        private readonly AppDbContext _context;
        private readonly IBlogService _blogService;
        public BlogController(AppDbContext context, IBlogService service)
        {
            _context = context;
            _blogService = service;
        }

        public IActionResult Create()
        {
            return View(); // menampilkan kolom inputan
        }

        [HttpPost]
        public IActionResult CreateAsync(Blog parameter, IFormFile image)
        {
            if (ModelState.IsValid) 
            {
                // proses masukan ke database

                // parameter.Id = BuatPrimary.primary(); // untuk membuat primary key dari helper

                // string nama = User.GetUsername();

                // parameter.User = _context.Tb_User.FirstOrDefault(x => x.Username == nama);



                // _context.Add(parameter);
                //await _context.SaveChangesAsync();

                _blogService.BuatBlog(parameter, User.GetUsername(), image);

                return Redirect("Index"); // menerima inputan
            }

            return View(parameter);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var cari = _context.Tb_Blog.Where(x => x.Id == id).FirstOrDefault();

            if(cari == null)
            {
                return NotFound();
            }

            _context.Tb_Blog.Remove(cari);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            var data = new BlogDashboard();

            data.blog = _context.Tb_Blog.Include(x => x.User).ToList();
            data.user = _context.Tb_User.Include(x => x.Roles).ToList();
            //var data = _context.Tb_Blog.ToList();
            return View(data);
        }

        public IActionResult DetailsBlog(int id)
        {
            var cari = _context.Tb_Blog.FirstOrDefault(x => x.Id == id);

            if (cari == null)
            {
                return NotFound();
            }

            var data = new DetailBlog();

            data.blog = _context.Tb_Blog.Where(x => x.Id == id).ToList();


            return View(data) ;

        }
      
        public async Task<IActionResult> Ubah(int id)
        {
            //var cari = await _context.Tb_Blog.FirstOrDefaultAsync(x => x.Id == id);
            var cari = await _blogService.TampilBLogById(id);

            if (cari == null)
            {
                return NotFound();
            }

            return View(cari);
        }

        [HttpPost]

        public async Task<IActionResult> Ubah(Blog data)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //_context.Tb_Blog.Update(data);
                    //await _context.SaveChangesAsync();

                    await _blogService.UpdateBlogAsync(data);
                }
                catch
                {
                    return NotFound();
                }
                return RedirectToAction("Index");
                 
            }
            return View(data);
        }

    }
}

WebApplication(ASP-MVC)/Views/Blog/Partial/SelectBlog.cshtml
@model BlogDashboard


<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Tabel Blog</h4>
                        <div class="table-responsive">
                            <p>
                                <a asp-action="Create">Create New</a>
                            </p>
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>
                                            ID
                                        </th>
                                        <th>
                                            Title
                                        </th>
                                        <th>
                                            Create Date
                                        </th>
                                        <th>
                                            Status
                                        </th>
                                        <th>
                                            User
                                        </th>
                                        <th> Option</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.blog)
                                    {
                                        <tr>
                                            <td>
                                                @item.Id
                                            </td>
                                            <td>
                                                @item.Title
                                            </td>
                                            <td>
                                                @item.CreateDate
                                            </td>
                                            <td>
                                                @item.Status
                                            </td>
                                            <td>
                                                @item.User.Username
                                            </td>
                                            <td>
                                                <a asp-action="Ubah" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                                                <a asp-controller="Blog" asp-action="DetailsBlog" asp-route-id="@item.Id" class="btn btn-info">Details</a>
                                                <a asp-action="Delete" asp-route-id="@item.Id" 
                                                   class="btn btn-warning" title="Hapus" 
                                                   onclick="if (!confirm('Yakin Akan Menghapus Blog ini ?')) { return false; }">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication(ASP-MVC)/Views/Blog/Partial/SelectUser.cshtml
@model BlogDashboard

<br />

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Tabel User</h4>
                        <div class="table-responsive">
                            <p>
                                <a asp-action="Create">Create New</a>
                            </p>
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>
                                            Username
                                        </th>
                                        <th>
                                            Password
                                        </th>
                                        <th> Option</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.user)
                                    {
                                        <tr>
                                            <td>
                                                @item.Username
                                            </td>
                                            <td>
                                                @item.Password
                                            </td>
                                            <td>
                                                <a asp-route-id="@item.Username" class="btn btn-primary">Edit</a>
                                                <a asp-route-id="@item.Username" class="btn btn-info">Details</a>
                                                <a asp-route-id="@item.Username" class="btn btn-warning">Delete</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>