WebApplication(ASP-MVC)/Controllers/AkunController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebApplication_ASP_MVC_.Helper;
using WebApplication_ASP_MVC_.Models;
using WebApplication_ASP_MVC_.Services;

namespace WebApplication_ASP_MVC_.Controllers
{
    public class AkunController : Controller
    {
        private readonly AppDbContext _context;
        private readonly EmailService _email;
        public AkunController(AppDbContext context,EmailService e)
        {
            _context = context;
            _email = e;
        }

        public IActionResult Daftar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Daftar(User datanya)
        {
            int OTP = BanyakBantuan.BuatOTP();

            bool hasil = _email.KirimEmail(datanya.Email, "Konfirmasi Daftar","<h1 style='color:red'> Assalamulaikum </h1>" + OTP);

            _context.Add(datanya);
            _context.SaveChanges();

            return RedirectToAction("Masuk");
        }

        public IActionResult Masuk()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Masuk(User datanya)
        {
            //var cari = _context.Tb_User.Where(carii => carii.Username == datanya.Username
            //                                           && carii.Password == carii.Password
            //                                  ).FirstOrDefault();
            //if (cari != null)
            //{
            //    return RedirectToAction(controllerName: "Blog", actionName: "Index");
            //}

            var cariUsername = _context.Tb_User.Where(x => x.Username == datanya.Username).FirstOrDefault();

            if (cariUsername != null)
            {
                var cekPassword = _context.Tb_User.Where(x => x.Username == datanya.Username
                                                         && x.Password == datanya.Password)
                                                         .Include(x2 => x2.Roles).FirstOrDefault();

                // proses tampungan data

                if (cekPassword != null)
                {
                    var daftar = new List<Claim>
                    {
                        new Claim ("Username", cariUsername.Username),
                        new Claim("Role", cariUsername.Roles.Name)
                    };

                    // proses daftar Auth

                    await HttpContext.SignInAsync(
                        new ClaimsPrincipal(
                            new ClaimsIdentity(daftar, "Cookie", "Username", "Role")
                        )
                    );

                    if (cariUsername.Roles.Id == "1")
                    {
                        return Redirect("/admin/home");
                    }else if(cariUsername.Roles.Id == "2")
                    {
                        return Redirect("/user/home");
                    }

                    return RedirectToAction(controllerName: "Blog", actionName: "Index");
                }
                ViewBag.pesan = "Password Salah !";
                return View(datanya);
            }

            ViewBag.pesan = "Username Salah !";
            return View(datanya);
        }
        
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return Redirect("/");
        }
    }
}

WebApplication(ASP-MVC)/Views/Shared/_Layout.cshtml
@using WebApplication_ASP_MVC_.Helper

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication_ASP_MVC_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication_ASP_MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-md-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Show Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Create">Create Blog</a>
                        </li>
                    </ul>
                    <div class="justify-content-end">          
                        <ul class="navbar-nav flex-md-grow-1">
                            @{
                                string cek = User.GetUsername();
                                if (cek != "")
                                {
                                    <b>@User.GetUsername()</b>
                                    <li class="nav-item ">
                                        <a href="/Akun/Logout"
                                         class="text-danger" style="margin-left:10px" onclick="if (!confirm('Yakin Untuk Keluar')) { return false; }">Logout</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item ">
                                        <a class="nav-link text-white btn btn-primary" asp-area="" asp-controller="Akun" asp-action="Masuk">Sign in</a>
                                    </li>
                                }
                            }

                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted font-weight-bold">
        <div class="container">
            &copy; 2021 - WebApplication_ASP_MVC_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 

WebApplication(ASP-MVC)/Views/Shared/_LayoutAkun.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> ASP_MVC | Registration Page</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
</head>
<body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a asp-controller="Home" asp-action="Index"><b>ASP_MVC</b></a>
        </div>

        @RenderBody()

    </div>
    <!-- /.register-box -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
</body>
</html>